-- 060_redundancy_wrongful_dismissal_rules.sql
-- Source-backed initial DB coverage for two additional UK employment modules.
--
-- These rows move redundancy and wrongful dismissal from "planned" to "partial".
-- They do NOT make the modules production-supported: workflow proof, full source
-- corpus, document paths, RAG/Graph RAG coverage, and legal accuracy tests remain
-- required before either module can be marked production.

INSERT INTO rules
  (rule_key, claim_type, jurisdiction, jurisdiction_code, domain, country_code,
   value_numeric, value_text, unit, description, authority_type, authority_ref, authority_url,
   effective_from, effective_to, is_prospective, verification_status, last_verified_at,
   legal_system, applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni,
   is_current)
VALUES
 ('wrongful_dismissal.notice_qualifying_period_months','wrongful_dismissal','EW','GB','employment_uk','GB',
  1, NULL, 'months',
  'Statutory minimum notice under ERA 1996 s.86 applies after one month of continuous employment.',
  'legislation','ERA 1996 s.86','https://www.legislation.gov.uk/ukpga/1996/18/section/86',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('wrongful_dismissal.max_statutory_notice_weeks','wrongful_dismissal','EW','GB','employment_uk','GB',
  12, NULL, 'weeks',
  'ERA 1996 s.86 statutory minimum notice scales by service and is capped at twelve weeks.',
  'legislation','ERA 1996 s.86','https://www.legislation.gov.uk/ukpga/1996/18/section/86',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('wrongful_dismissal.statutory_notice_formula','wrongful_dismissal','EW','GB','employment_uk','GB',
  NULL,
  'At least one week after one month service; two weeks after two years; then one additional week for each further complete year, up to twelve weeks.',
  'formula',
  'Statutory minimum employer notice formula. Contractual notice may be longer and must also be checked.',
  'legislation','ERA 1996 s.86','https://www.legislation.gov.uk/ukpga/1996/18/section/86',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('wrongful_dismissal.et_time_limit_months','wrongful_dismissal','EW','GB','employment_uk','GB',
  3, NULL, 'months',
  'Employment tribunal breach-of-contract complaints under the 1994 Extension of Jurisdiction Order are normally subject to a three-month tribunal time limit.',
  'legislation','Employment Tribunals Extension of Jurisdiction (England and Wales) Order 1994 arts.3,7','https://www.legislation.gov.uk/uksi/1994/1623',
  DATE '1994-07-12', NULL, false, 'verified', now(),
  'England and Wales', false, true, false, false, true),
 ('wrongful_dismissal.et_contract_claim_scope','wrongful_dismissal','EW','GB','employment_uk','GB',
  NULL,
  'Employment tribunal contractual jurisdiction is limited to qualifying breach-of-contract claims arising or outstanding on termination. County court limitation may differ.',
  'qualitative',
  'Scope guard for wrongful-dismissal self-help assessment; routes larger/complex contract claims to specialist advice.',
  'legislation','Employment Tribunals Extension of Jurisdiction (England and Wales) Order 1994 art.3','https://www.legislation.gov.uk/uksi/1994/1623/article/3',
  DATE '1994-07-12', NULL, false, 'verified', now(),
  'England and Wales', false, true, false, false, true),
 ('redundancy.payment_right','redundancy','EW','GB','employment_uk','GB',
  NULL,
  'An employer must pay a redundancy payment where the statutory conditions are met, including dismissal by reason of redundancy.',
  'qualitative',
  'Core statutory redundancy payment right.',
  'legislation','ERA 1996 s.135','https://www.legislation.gov.uk/ukpga/1996/18/section/135',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('redundancy.definition','redundancy','EW','GB','employment_uk','GB',
  NULL,
  'Redundancy covers closure of business/workplace or reduced requirements for employees to do work of a particular kind.',
  'qualitative',
  'Statutory definition of dismissal by reason of redundancy.',
  'legislation','ERA 1996 s.139','https://www.legislation.gov.uk/ukpga/1996/18/section/139',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('redundancy.qualifying_period_years','redundancy','EW','GB','employment_uk','GB',
  2, NULL, 'years',
  'Employee normally needs at least two years continuous service ending with the relevant date to qualify for a statutory redundancy payment.',
  'legislation','ERA 1996 s.155','https://www.legislation.gov.uk/ukpga/1996/18/section/155',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('redundancy.time_limit_months','redundancy','EW','GB','employment_uk','GB',
  6, NULL, 'months',
  'Statutory redundancy payment claims generally require action before the end of six months beginning with the relevant date, subject to statutory conditions.',
  'legislation','ERA 1996 s.164','https://www.legislation.gov.uk/ukpga/1996/18/section/164',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('redundancy.payment_formula','redundancy','EW','GB','employment_uk','GB',
  NULL,
  'Statutory redundancy payment is calculated by complete years of service with age bands: 0.5 week under 22, 1 week aged 22-40, 1.5 weeks aged 41+, subject to statutory limits.',
  'formula',
  'Initial formula anchor; monetary caps must be pulled from effective-dated week-pay cap rules, not hardcoded.',
  'legislation','ERA 1996 s.162','https://www.legislation.gov.uk/ukpga/1996/18/section/162',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true)
ON CONFLICT (rule_key, jurisdiction, effective_from) DO UPDATE SET
  value_numeric=EXCLUDED.value_numeric,
  value_text=EXCLUDED.value_text,
  unit=EXCLUDED.unit,
  description=EXCLUDED.description,
  authority_type=EXCLUDED.authority_type,
  authority_ref=EXCLUDED.authority_ref,
  authority_url=EXCLUDED.authority_url,
  effective_to=EXCLUDED.effective_to,
  is_prospective=EXCLUDED.is_prospective,
  verification_status=EXCLUDED.verification_status,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  domain=EXCLUDED.domain,
  country_code=EXCLUDED.country_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni,
  is_current=EXCLUDED.is_current,
  last_verified_at=now();

INSERT INTO legislation
  (act_title, leg_type, year, chapter, section_ref, jurisdiction, heading,
   body_text, chunk_index, source_url, effective_from, last_verified_at,
   content_hash, country_code, domain, source_type, licence_status,
   parser_type, parent_source_id, jurisdiction_code, legal_system,
   applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni)
VALUES
 ('Employment Rights Act 1996','primary',1996,'18','86','EW',
  'Rights of employer and employee to minimum notice',
  'Section 86 sets the statutory minimum notice required to terminate employment after one month continuous employment, scaling by length of service up to twelve weeks.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/86',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s86 minimum notice'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','135','EW',
  'The right',
  'Section 135 creates the statutory right to a redundancy payment where an employee is dismissed by reason of redundancy and the statutory conditions are met.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/135',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s135 redundancy payment right'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','139','EW',
  'Redundancy',
  'Section 139 defines dismissal by reason of redundancy, including business closure, workplace closure, and reduced need for employees to do work of a particular kind.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/139',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s139 redundancy definition'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','155','EW',
  'Qualifying period of employment',
  'Section 155 requires at least two years continuous employment ending with the relevant date for statutory redundancy payment entitlement.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/155',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s155 redundancy qualifying period'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','162','EW',
  'Amount of redundancy payment',
  'Section 162 sets the statutory redundancy payment calculation using complete years of service, age bands, and week-pay limits.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/162',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s162 redundancy payment calculation'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','164','EW',
  'Claims for redundancy payment',
  'Section 164 sets the statutory route and time conditions for claiming a redundancy payment.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/164',
  DATE '1996-08-22', now(), encode(sha256('ERA 1996 s164 redundancy claim time limit'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Tribunals Extension of Jurisdiction (England and Wales) Order 1994','secondary',1994,'1623','article/3','EW',
  'Extension of jurisdiction',
  'Article 3 enables qualifying breach-of-contract claims connected with termination of employment to be brought in the employment tribunal.',
  0,'https://www.legislation.gov.uk/uksi/1994/1623/article/3',
  DATE '1994-07-12', now(), encode(sha256('EJ Order 1994 article 3 contract jurisdiction'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','England and Wales',false,true,false,false),
 ('Employment Tribunals Extension of Jurisdiction (England and Wales) Order 1994','secondary',1994,'1623','article/7','EW',
  'Time within which proceedings may be brought',
  'Article 7 sets the time limit for qualifying employment tribunal breach-of-contract proceedings.',
  0,'https://www.legislation.gov.uk/uksi/1994/1623/article/7',
  DATE '1994-07-12', now(), encode(sha256('EJ Order 1994 article 7 contract time limit'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','England and Wales',false,true,false,false)
ON CONFLICT (source_url, chunk_index) DO UPDATE SET
  act_title=EXCLUDED.act_title,
  leg_type=EXCLUDED.leg_type,
  year=EXCLUDED.year,
  chapter=EXCLUDED.chapter,
  section_ref=EXCLUDED.section_ref,
  jurisdiction=EXCLUDED.jurisdiction,
  heading=EXCLUDED.heading,
  body_text=EXCLUDED.body_text,
  effective_from=EXCLUDED.effective_from,
  last_verified_at=now(),
  content_hash=EXCLUDED.content_hash,
  country_code=EXCLUDED.country_code,
  domain=EXCLUDED.domain,
  source_type=EXCLUDED.source_type,
  licence_status=EXCLUDED.licence_status,
  parser_type=EXCLUDED.parser_type,
  parent_source_id=EXCLUDED.parent_source_id,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni;

UPDATE employment_modules
SET status = 'partial',
    updated_at = now()
WHERE module_key IN ('redundancy', 'wrongful_dismissal')
  AND status <> 'production';
