-- 061_working_time_holiday_nmw_flexible_rules.sql
-- Initial verified DB coverage for four additional UK employment modules.
--
-- These modules remain partial. This migration adds statutory anchors and
-- non-volatile rules only; current NMW rate tables and full workflow/RAG/document
-- proof are still required before production support.

INSERT INTO rules
  (rule_key, claim_type, jurisdiction, jurisdiction_code, domain, country_code,
   value_numeric, value_text, unit, description, authority_type, authority_ref, authority_url,
   effective_from, effective_to, is_prospective, verification_status, last_verified_at,
   legal_system, applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni,
   is_current)
VALUES
 ('working_time.max_weekly_hours','working_time','EW','GB','employment_uk','GB',
  48, NULL, 'hours',
  'Average weekly working time limit unless a valid opt-out or exception applies.',
  'legislation','Working Time Regulations 1998 reg.4','https://www.legislation.gov.uk/uksi/1998/1833/regulation/4',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('working_time.daily_rest_hours','working_time','EW','GB','employment_uk','GB',
  11, NULL, 'hours',
  'Adult workers are generally entitled to 11 consecutive hours daily rest in each 24-hour period.',
  'legislation','Working Time Regulations 1998 reg.10','https://www.legislation.gov.uk/uksi/1998/1833/regulation/10',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('working_time.weekly_rest_hours','working_time','EW','GB','employment_uk','GB',
  24, NULL, 'hours',
  'Adult workers are generally entitled to an uninterrupted weekly rest period, subject to regulation wording and exceptions.',
  'legislation','Working Time Regulations 1998 reg.11','https://www.legislation.gov.uk/uksi/1998/1833/regulation/11',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('working_time.rest_break_minutes','working_time','EW','GB','employment_uk','GB',
  20, NULL, 'minutes',
  'Adult workers whose daily working time exceeds six hours are generally entitled to a rest break.',
  'legislation','Working Time Regulations 1998 reg.12','https://www.legislation.gov.uk/uksi/1998/1833/regulation/12',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('working_time.rest_break_trigger_hours','working_time','EW','GB','employment_uk','GB',
  6, NULL, 'hours',
  'Rest-break entitlement is triggered where daily working time is more than six hours, subject to exceptions.',
  'legislation','Working Time Regulations 1998 reg.12','https://www.legislation.gov.uk/uksi/1998/1833/regulation/12',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('holiday_pay.annual_leave_weeks','holiday_pay','EW','GB','employment_uk','GB',
  4, NULL, 'weeks',
  'Core statutory annual leave entitlement under regulation 13.',
  'legislation','Working Time Regulations 1998 reg.13','https://www.legislation.gov.uk/uksi/1998/1833/regulation/13',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('holiday_pay.additional_leave_weeks','holiday_pay','EW','GB','employment_uk','GB',
  1.6, NULL, 'weeks',
  'Additional annual leave entitlement under regulation 13A, giving the familiar 5.6-week total for many workers.',
  'legislation','Working Time Regulations 1998 reg.13A','https://www.legislation.gov.uk/uksi/1998/1833/regulation/13A',
  DATE '2007-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('holiday_pay.total_annual_leave_weeks','holiday_pay','EW','GB','employment_uk','GB',
  5.6, NULL, 'weeks',
  'Combined statutory annual leave from regulations 13 and 13A for many workers, subject to worker category and statutory limits.',
  'legislation','Working Time Regulations 1998 regs.13,13A','https://www.legislation.gov.uk/uksi/1998/1833/part/II',
  DATE '2009-04-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('holiday_pay.termination_payment_in_lieu','holiday_pay','EW','GB','employment_uk','GB',
  NULL, 'payment_due_for_untaken_leave_on_termination', 'qualitative',
  'Regulation 14 governs payment in lieu of untaken statutory leave on termination.',
  'legislation','Working Time Regulations 1998 reg.14','https://www.legislation.gov.uk/uksi/1998/1833/regulation/14',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('holiday_pay.tribunal_complaint_route','holiday_pay','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_available', 'qualitative',
  'Regulation 30 provides the employment tribunal complaint route for specified Working Time Regulations breaches.',
  'legislation','Working Time Regulations 1998 reg.30','https://www.legislation.gov.uk/uksi/1998/1833/regulation/30',
  DATE '1998-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('national_minimum_wage.worker_entitlement','national_minimum_wage','EW','GB','employment_uk','GB',
  NULL, 'worker_qualifies_for_national_minimum_wage', 'qualitative',
  'A qualifying worker must be paid at least the national minimum wage for work in a pay reference period.',
  'legislation','National Minimum Wage Act 1998 s.1','https://www.legislation.gov.uk/ukpga/1998/39/section/1',
  DATE '1999-04-01', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('national_minimum_wage.worker_definition','national_minimum_wage','EW','GB','employment_uk','GB',
  NULL, 'worker_status_required', 'qualitative',
  'NMWA 1998 uses a worker concept that includes contracts to perform work personally, subject to statutory exclusions.',
  'legislation','National Minimum Wage Act 1998 s.54','https://www.legislation.gov.uk/ukpga/1998/39/section/54',
  DATE '1999-04-01', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('national_minimum_wage.records_right','national_minimum_wage','EW','GB','employment_uk','GB',
  NULL, 'worker_right_to_records_access', 'qualitative',
  'A worker has statutory rights relating to access to records for NMW enforcement.',
  'legislation','National Minimum Wage Act 1998 s.10','https://www.legislation.gov.uk/ukpga/1998/39/section/10',
  DATE '1999-04-01', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('national_minimum_wage.arrears_anchor','national_minimum_wage','EW','GB','employment_uk','GB',
  NULL, 'arrears_and_remuneration_due_must_be_calculated_from_current_effective_rates', 'qualitative',
  'NMW arrears/remuneration calculations must use the applicable effective-dated rates, not model memory.',
  'legislation','National Minimum Wage Act 1998 s.17','https://www.legislation.gov.uk/ukpga/1998/39/section/17',
  DATE '1999-04-01', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('national_minimum_wage.enforcement_notice_anchor','national_minimum_wage','EW','GB','employment_uk','GB',
  NULL, 'enforcement_notice_and_appeal_routes_exist', 'qualitative',
  'NMW enforcement-notice and appeal provisions exist; user workflow must distinguish HMRC enforcement from tribunal/civil routes.',
  'legislation','National Minimum Wage Act 1998 s.19','https://www.legislation.gov.uk/ukpga/1998/39/section/19',
  DATE '1999-04-01', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('flexible_working.day_one_application_right','flexible_working','EW','GB','employment_uk','GB',
  0, NULL, 'days_service',
  'Current statutory flexible working request regime is a day-one right for employees.',
  'legislation','ERA 1996 s.80F + Flexible Working (Amendment) Regulations 2023','https://www.legislation.gov.uk/ukpga/1996/18/section/80F',
  DATE '2024-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('flexible_working.max_requests_per_12_months','flexible_working','EW','GB','employment_uk','GB',
  2, NULL, 'requests',
  'Employee may make up to two statutory flexible working requests to the same employer in a 12-month period.',
  'legislation','Employment Relations (Flexible Working) Act 2023 s.1','https://www.legislation.gov.uk/ukpga/2023/33/section/1',
  DATE '2024-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('flexible_working.decision_period_months','flexible_working','EW','GB','employment_uk','GB',
  2, NULL, 'months',
  'Employer should decide a statutory flexible working request within two months unless an extension is agreed.',
  'legislation','ERA 1996 s.80G + Employment Relations (Flexible Working) Act 2023','https://www.legislation.gov.uk/ukpga/1996/18/section/80G',
  DATE '2024-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('flexible_working.consultation_required_before_refusal','flexible_working','EW','GB','employment_uk','GB',
  NULL, 'consultation_required_before_refusal', 'qualitative',
  'Employer must not refuse a statutory flexible working request without consulting the employee.',
  'legislation','ERA 1996 s.80G + Employment Relations (Flexible Working) Act 2023','https://www.legislation.gov.uk/ukpga/1996/18/section/80G',
  DATE '2024-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('flexible_working.tribunal_complaint_route','flexible_working','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_available', 'qualitative',
  'ERA 1996 s.80H provides the complaint route where statutory flexible working duties are breached.',
  'legislation','ERA 1996 s.80H','https://www.legislation.gov.uk/ukpga/1996/18/section/80H',
  DATE '2024-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true)
ON CONFLICT (rule_key, jurisdiction, effective_from) DO UPDATE SET
  value_numeric=EXCLUDED.value_numeric,
  value_text=EXCLUDED.value_text,
  unit=EXCLUDED.unit,
  description=EXCLUDED.description,
  authority_type=EXCLUDED.authority_type,
  authority_ref=EXCLUDED.authority_ref,
  authority_url=EXCLUDED.authority_url,
  effective_to=EXCLUDED.effective_to,
  is_prospective=EXCLUDED.is_prospective,
  verification_status=EXCLUDED.verification_status,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  domain=EXCLUDED.domain,
  country_code=EXCLUDED.country_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni,
  is_current=EXCLUDED.is_current,
  last_verified_at=now();

INSERT INTO legislation
  (act_title, leg_type, year, chapter, section_ref, jurisdiction, heading,
   body_text, chunk_index, source_url, effective_from, last_verified_at,
   content_hash, country_code, domain, source_type, licence_status,
   parser_type, parent_source_id, jurisdiction_code, legal_system,
   applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni)
VALUES
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/4','EW',
  'Maximum weekly working time',
  'Regulation 4 contains the average weekly working time limit, subject to opt-out and exceptions.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/4',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg4 maximum weekly working time'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/10','EW',
  'Daily rest',
  'Regulation 10 contains the daily rest entitlement.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/10',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg10 daily rest'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/11','EW',
  'Weekly rest period',
  'Regulation 11 contains the weekly rest entitlement.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/11',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg11 weekly rest'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/12','EW',
  'Rest breaks',
  'Regulation 12 contains rest-break rights during the working day.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/12',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg12 rest breaks'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/13','EW',
  'Entitlement to annual leave',
  'Regulation 13 contains the core annual leave entitlement.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/13',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg13 annual leave'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/13A','EW',
  'Entitlement to additional annual leave',
  'Regulation 13A contains additional annual leave entitlement.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/13A',
  DATE '2007-10-01', now(), encode(sha256('WTR 1998 reg13A additional annual leave'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/14','EW',
  'Compensation related to entitlement to leave',
  'Regulation 14 governs payment in lieu of untaken statutory leave on termination.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/14',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg14 termination holiday pay'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Working Time Regulations 1998','secondary',1998,'1833','regulation/30','EW',
  'Remedies',
  'Regulation 30 provides employment tribunal remedies for specified Working Time Regulations breaches.',
  0,'https://www.legislation.gov.uk/uksi/1998/1833/regulation/30',
  DATE '1998-10-01', now(), encode(sha256('WTR 1998 reg30 tribunal remedies'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('National Minimum Wage Act 1998','primary',1998,'39','1','EW',
  'The national minimum wage',
  'Section 1 creates the entitlement for a qualifying worker to be remunerated at not less than the national minimum wage.',
  0,'https://www.legislation.gov.uk/ukpga/1998/39/section/1',
  DATE '1999-04-01', now(), encode(sha256('NMWA 1998 s1 entitlement'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','United Kingdom',true,true,true,true),
 ('National Minimum Wage Act 1998','primary',1998,'39','10','EW',
  'Worker right of access to records',
  'Section 10 provides worker access to records relevant to national minimum wage enforcement.',
  0,'https://www.legislation.gov.uk/ukpga/1998/39/section/10',
  DATE '1999-04-01', now(), encode(sha256('NMWA 1998 s10 records access'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','United Kingdom',true,true,true,true),
 ('National Minimum Wage Act 1998','primary',1998,'39','17','EW',
  'Non-compliance: worker underpaid',
  'Section 17 anchors arrears/remuneration consequences where a worker has been paid below the applicable minimum wage.',
  0,'https://www.legislation.gov.uk/ukpga/1998/39/section/17',
  DATE '1999-04-01', now(), encode(sha256('NMWA 1998 s17 arrears'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','United Kingdom',true,true,true,true),
 ('National Minimum Wage Act 1998','primary',1998,'39','19','EW',
  'Appeals against notices of underpayment',
  'Section 19 provides appeal machinery for notices of underpayment.',
  0,'https://www.legislation.gov.uk/ukpga/1998/39/section/19',
  DATE '1999-04-01', now(), encode(sha256('NMWA 1998 s19 appeals'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','United Kingdom',true,true,true,true),
 ('National Minimum Wage Act 1998','primary',1998,'39','54','EW',
  'Meaning of worker, employee etc.',
  'Section 54 contains definitions including worker for National Minimum Wage Act purposes.',
  0,'https://www.legislation.gov.uk/ukpga/1998/39/section/54',
  DATE '1999-04-01', now(), encode(sha256('NMWA 1998 s54 worker definition'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','United Kingdom',true,true,true,true),
 ('Employment Rights Act 1996','primary',1996,'18','80F','EW',
  'Statutory right to request contract variation',
  'Section 80F contains the statutory right to make a flexible working request.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80F',
  DATE '2024-04-06', now(), encode(sha256('ERA 1996 s80F flexible working request'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80G','EW',
  'Employer duties in relation to application',
  'Section 80G contains employer duties for statutory flexible working requests.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80G',
  DATE '2024-04-06', now(), encode(sha256('ERA 1996 s80G flexible working duties'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80H','EW',
  'Complaints to employment tribunals',
  'Section 80H contains the complaint route for breach of statutory flexible working request duties.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80H',
  DATE '2024-04-06', now(), encode(sha256('ERA 1996 s80H flexible working tribunal complaint'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk',
  'GB','Great Britain',true,true,true,false)
ON CONFLICT (source_url, chunk_index) DO UPDATE SET
  act_title=EXCLUDED.act_title,
  leg_type=EXCLUDED.leg_type,
  year=EXCLUDED.year,
  chapter=EXCLUDED.chapter,
  section_ref=EXCLUDED.section_ref,
  jurisdiction=EXCLUDED.jurisdiction,
  heading=EXCLUDED.heading,
  body_text=EXCLUDED.body_text,
  effective_from=EXCLUDED.effective_from,
  last_verified_at=now(),
  content_hash=EXCLUDED.content_hash,
  country_code=EXCLUDED.country_code,
  domain=EXCLUDED.domain,
  source_type=EXCLUDED.source_type,
  licence_status=EXCLUDED.licence_status,
  parser_type=EXCLUDED.parser_type,
  parent_source_id=EXCLUDED.parent_source_id,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni;

UPDATE employment_modules
SET status = 'partial',
    updated_at = now()
WHERE module_key IN ('working_time', 'holiday_pay', 'national_minimum_wage', 'flexible_working')
  AND status <> 'production';
