-- 062_equality_whistleblowing_rules.sql
-- Initial verified DB coverage for discrimination, pregnancy/maternity
-- discrimination, equal pay, and whistleblowing.
--
-- These modules remain partial. They need full workflow, RAG/Graph RAG,
-- source-corpus, case-law, remedies, limitation, document, and legal matrix proof
-- before production exposure.

INSERT INTO rules
  (rule_key, claim_type, jurisdiction, jurisdiction_code, domain, country_code,
   value_numeric, value_text, unit, description, authority_type, authority_ref, authority_url,
   effective_from, effective_to, is_prospective, verification_status, last_verified_at,
   legal_system, applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni,
   is_current)
VALUES
 ('discrimination.protected_characteristics','discrimination','EW','GB','employment_uk','GB',
  NULL, 'age; disability; gender reassignment; marriage and civil partnership; pregnancy and maternity; race; religion or belief; sex; sexual orientation', 'list',
  'Protected characteristics for Equality Act 2010 discrimination claims.',
  'legislation','Equality Act 2010 s.4','https://www.legislation.gov.uk/ukpga/2010/15/section/4',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.direct_discrimination','discrimination','EW','GB','employment_uk','GB',
  NULL, 'less_favourable_treatment_because_of_protected_characteristic', 'qualitative',
  'Direct discrimination statutory anchor.',
  'legislation','Equality Act 2010 s.13','https://www.legislation.gov.uk/ukpga/2010/15/section/13',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.indirect_discrimination','discrimination','EW','GB','employment_uk','GB',
  NULL, 'pcp_disadvantage_and_justification_test', 'qualitative',
  'Indirect discrimination statutory anchor.',
  'legislation','Equality Act 2010 s.19','https://www.legislation.gov.uk/ukpga/2010/15/section/19',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.harassment','discrimination','EW','GB','employment_uk','GB',
  NULL, 'unwanted_conduct_related_to_relevant_protected_characteristic_or_sexual_harassment', 'qualitative',
  'Harassment statutory anchor.',
  'legislation','Equality Act 2010 s.26','https://www.legislation.gov.uk/ukpga/2010/15/section/26',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.victimisation','discrimination','EW','GB','employment_uk','GB',
  NULL, 'detriment_because_of_protected_act', 'qualitative',
  'Victimisation statutory anchor.',
  'legislation','Equality Act 2010 s.27','https://www.legislation.gov.uk/ukpga/2010/15/section/27',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.work_context','discrimination','EW','GB','employment_uk','GB',
  NULL, 'employees_and_applicants_work_context', 'qualitative',
  'Part 5 work context anchor for employees and applicants.',
  'legislation','Equality Act 2010 s.39','https://www.legislation.gov.uk/ukpga/2010/15/section/39',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.tribunal_jurisdiction','discrimination','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_part_5_work_jurisdiction', 'qualitative',
  'Employment tribunal jurisdiction anchor for Equality Act work claims.',
  'legislation','Equality Act 2010 s.120','https://www.legislation.gov.uk/ukpga/2010/15/section/120',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('discrimination.time_limit_months','discrimination','EW','GB','employment_uk','GB',
  3, NULL, 'months',
  'Primary tribunal limitation period anchor for Equality Act claims, subject to just-and-equitable extension and date/continuing-act analysis.',
  'legislation','Equality Act 2010 s.123','https://www.legislation.gov.uk/ukpga/2010/15/section/123',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('pregnancy_maternity_discrimination.unfavourable_treatment','pregnancy_maternity_discrimination','EW','GB','employment_uk','GB',
  NULL, 'unfavourable_treatment_because_of_pregnancy_maternity_leave_or_related_illness', 'qualitative',
  'Pregnancy and maternity discrimination statutory anchor in work cases.',
  'legislation','Equality Act 2010 s.18','https://www.legislation.gov.uk/ukpga/2010/15/section/18',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('pregnancy_maternity_discrimination.work_context','pregnancy_maternity_discrimination','EW','GB','employment_uk','GB',
  NULL, 'employees_and_applicants_work_context', 'qualitative',
  'Part 5 work context anchor for employees and applicants.',
  'legislation','Equality Act 2010 s.39','https://www.legislation.gov.uk/ukpga/2010/15/section/39',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('pregnancy_maternity_discrimination.tribunal_jurisdiction','pregnancy_maternity_discrimination','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_part_5_work_jurisdiction', 'qualitative',
  'Employment tribunal jurisdiction anchor for Equality Act work claims.',
  'legislation','Equality Act 2010 s.120','https://www.legislation.gov.uk/ukpga/2010/15/section/120',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('pregnancy_maternity_discrimination.time_limit_months','pregnancy_maternity_discrimination','EW','GB','employment_uk','GB',
  3, NULL, 'months',
  'Primary Equality Act tribunal time limit anchor; pregnancy/maternity claims require careful date and continuing-act analysis.',
  'legislation','Equality Act 2010 s.123','https://www.legislation.gov.uk/ukpga/2010/15/section/123',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('pregnancy_maternity_discrimination.characteristic_anchor','pregnancy_maternity_discrimination','EW','GB','employment_uk','GB',
  NULL, 'pregnancy_and_maternity_protected_characteristic', 'qualitative',
  'Pregnancy and maternity is a protected characteristic under the Equality Act 2010.',
  'legislation','Equality Act 2010 s.4','https://www.legislation.gov.uk/ukpga/2010/15/section/4',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('equal_pay.equal_work','equal_pay','EW','GB','employment_uk','GB',
  NULL, 'like_work_work_rated_as_equivalent_or_work_of_equal_value', 'qualitative',
  'Equal work statutory anchor.',
  'legislation','Equality Act 2010 s.65','https://www.legislation.gov.uk/ukpga/2010/15/section/65',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('equal_pay.sex_equality_clause','equal_pay','EW','GB','employment_uk','GB',
  NULL, 'sex_equality_clause_implied_into_contract', 'qualitative',
  'Sex equality clause statutory anchor.',
  'legislation','Equality Act 2010 s.66','https://www.legislation.gov.uk/ukpga/2010/15/section/66',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('equal_pay.material_factor_defence','equal_pay','EW','GB','employment_uk','GB',
  NULL, 'material_factor_defence_anchor', 'qualitative',
  'Material factor defence statutory anchor.',
  'legislation','Equality Act 2010 s.69','https://www.legislation.gov.uk/ukpga/2010/15/section/69',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('equal_pay.tribunal_jurisdiction','equal_pay','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_equal_pay_jurisdiction', 'qualitative',
  'Employment tribunal jurisdiction anchor for Equality Act work/equal pay claims.',
  'legislation','Equality Act 2010 s.120','https://www.legislation.gov.uk/ukpga/2010/15/section/120',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('equal_pay.time_limit_months','equal_pay','EW','GB','employment_uk','GB',
  6, NULL, 'months',
  'Equal pay claim time limit anchor after end of employment in the standard case, subject to detailed statutory categories.',
  'legislation','Equality Act 2010 s.129','https://www.legislation.gov.uk/ukpga/2010/15/section/129',
  DATE '2010-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('whistleblowing.qualifying_disclosure','whistleblowing','EW','GB','employment_uk','GB',
  NULL, 'qualifying_disclosure_of_information_public_interest_and_relevant_failure', 'qualitative',
  'Qualifying disclosure statutory anchor.',
  'legislation','ERA 1996 s.43B','https://www.legislation.gov.uk/ukpga/1996/18/section/43B',
  DATE '1999-07-02', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('whistleblowing.protected_disclosure','whistleblowing','EW','GB','employment_uk','GB',
  NULL, 'protected_disclosure_made_under_statutory_channels', 'qualitative',
  'Protected disclosure statutory route anchor.',
  'legislation','ERA 1996 Part IVA','https://www.legislation.gov.uk/ukpga/1996/18/part/IVA',
  DATE '1999-07-02', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('whistleblowing.detriment_protection','whistleblowing','EW','GB','employment_uk','GB',
  NULL, 'worker_not_to_be_subject_to_detriment_for_protected_disclosure', 'qualitative',
  'Worker detriment protection statutory anchor.',
  'legislation','ERA 1996 s.47B','https://www.legislation.gov.uk/ukpga/1996/18/section/47B',
  DATE '1999-07-02', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('whistleblowing.automatic_unfair_dismissal','whistleblowing','EW','GB','employment_uk','GB',
  NULL, 'dismissal_for_protected_disclosure_automatically_unfair', 'qualitative',
  'Automatic unfair dismissal statutory anchor for protected disclosures.',
  'legislation','ERA 1996 s.103A','https://www.legislation.gov.uk/ukpga/1996/18/section/103A',
  DATE '1999-07-02', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('whistleblowing.complaint_route','whistleblowing','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_route_for_detriment', 'qualitative',
  'Complaint route statutory anchor for whistleblowing detriment.',
  'legislation','ERA 1996 s.48','https://www.legislation.gov.uk/ukpga/1996/18/section/48',
  DATE '1999-07-02', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true)
ON CONFLICT (rule_key, jurisdiction, effective_from) DO UPDATE SET
  value_numeric=EXCLUDED.value_numeric,
  value_text=EXCLUDED.value_text,
  unit=EXCLUDED.unit,
  description=EXCLUDED.description,
  authority_type=EXCLUDED.authority_type,
  authority_ref=EXCLUDED.authority_ref,
  authority_url=EXCLUDED.authority_url,
  effective_to=EXCLUDED.effective_to,
  is_prospective=EXCLUDED.is_prospective,
  verification_status=EXCLUDED.verification_status,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  domain=EXCLUDED.domain,
  country_code=EXCLUDED.country_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni,
  is_current=EXCLUDED.is_current,
  last_verified_at=now();

INSERT INTO legislation
  (act_title, leg_type, year, chapter, section_ref, jurisdiction, heading,
   body_text, chunk_index, source_url, effective_from, last_verified_at,
   content_hash, country_code, domain, source_type, licence_status,
   parser_type, parent_source_id, jurisdiction_code, legal_system,
   applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni)
VALUES
 ('Equality Act 2010','primary',2010,'15','4','EW','Protected characteristics',
  'Section 4 lists the protected characteristics for Equality Act 2010 purposes.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/4', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s4 protected characteristics'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','13','EW','Direct discrimination',
  'Section 13 defines direct discrimination.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/13', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s13 direct discrimination'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','18','EW','Pregnancy and maternity discrimination: work cases',
  'Section 18 defines pregnancy and maternity discrimination in work cases.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/18', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s18 pregnancy maternity work'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','19','EW','Indirect discrimination',
  'Section 19 defines indirect discrimination.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/19', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s19 indirect discrimination'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','26','EW','Harassment',
  'Section 26 defines harassment.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/26', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s26 harassment'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','27','EW','Victimisation',
  'Section 27 defines victimisation.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/27', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s27 victimisation'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','39','EW','Employees and applicants',
  'Section 39 applies Equality Act work protections to employees and applicants.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/39', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s39 work employees applicants'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','65','EW','Equal work',
  'Section 65 defines equal work for equal pay purposes.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/65', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s65 equal work'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','66','EW','Sex equality clause',
  'Section 66 provides for a sex equality clause in qualifying contracts.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/66', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s66 sex equality clause'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','69','EW','Defence of material factor',
  'Section 69 anchors the material factor defence in equal pay claims.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/69', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s69 material factor defence'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','120','EW','Jurisdiction',
  'Section 120 gives employment tribunals jurisdiction for Equality Act work claims.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/120', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s120 tribunal jurisdiction'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','123','EW','Time limits',
  'Section 123 anchors tribunal time limits for Equality Act claims.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/123', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s123 time limits'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Equality Act 2010','primary',2010,'15','129','EW','Time limits: equal pay',
  'Section 129 anchors time limits for equal pay claims.',
  0,'https://www.legislation.gov.uk/ukpga/2010/15/section/129', DATE '2010-10-01', now(),
  encode(sha256('Equality Act 2010 s129 equal pay time limits'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','43B','EW','Disclosures qualifying for protection',
  'Section 43B defines qualifying disclosures for whistleblowing protection.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/43B', DATE '1999-07-02', now(),
  encode(sha256('ERA 1996 s43B qualifying disclosure'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','47B','EW','Protected disclosures',
  'Section 47B protects workers from detriment for making protected disclosures.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/47B', DATE '1999-07-02', now(),
  encode(sha256('ERA 1996 s47B whistleblowing detriment'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','48','EW','Complaints to employment tribunals',
  'Section 48 provides complaint routes for detriment claims including protected disclosures.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/48', DATE '1999-07-02', now(),
  encode(sha256('ERA 1996 s48 whistleblowing complaints'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','103A','EW','Protected disclosure',
  'Section 103A makes dismissal for the reason of a protected disclosure automatically unfair.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/103A', DATE '1999-07-02', now(),
  encode(sha256('ERA 1996 s103A whistleblowing dismissal'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false)
ON CONFLICT (source_url, chunk_index) DO UPDATE SET
  act_title=EXCLUDED.act_title,
  leg_type=EXCLUDED.leg_type,
  year=EXCLUDED.year,
  chapter=EXCLUDED.chapter,
  section_ref=EXCLUDED.section_ref,
  jurisdiction=EXCLUDED.jurisdiction,
  heading=EXCLUDED.heading,
  body_text=EXCLUDED.body_text,
  effective_from=EXCLUDED.effective_from,
  last_verified_at=now(),
  content_hash=EXCLUDED.content_hash,
  country_code=EXCLUDED.country_code,
  domain=EXCLUDED.domain,
  source_type=EXCLUDED.source_type,
  licence_status=EXCLUDED.licence_status,
  parser_type=EXCLUDED.parser_type,
  parent_source_id=EXCLUDED.parent_source_id,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni;

UPDATE employment_modules
SET status = 'partial',
    updated_at = now()
WHERE module_key IN (
  'discrimination',
  'pregnancy_maternity_discrimination',
  'equal_pay',
  'whistleblowing'
)
AND status <> 'production';
