-- 063_family_leave_rules.sql
-- Initial verified DB coverage for maternity, paternity, parental leave, and
-- shared parental leave modules.
--
-- These modules remain partial. The 2025/2026 family-leave reforms are moving,
-- so this migration seeds stable statutory anchors and conservative current
-- high-level rules only. Full effective-dated eligibility/notice/pay matrices,
-- workflow proof, RAG/Graph RAG proof, and document proof are still required.

INSERT INTO rules
  (rule_key, claim_type, jurisdiction, jurisdiction_code, domain, country_code,
   value_numeric, value_text, unit, description, authority_type, authority_ref, authority_url,
   effective_from, effective_to, is_prospective, verification_status, last_verified_at,
   legal_system, applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni,
   is_current)
VALUES
 ('maternity_rights.ordinary_maternity_leave_anchor','maternity_rights','EW','GB','employment_uk','GB',
  NULL, 'ordinary_maternity_leave_right', 'qualitative',
  'ERA 1996 s.71 anchors ordinary maternity leave entitlement.',
  'legislation','ERA 1996 s.71','https://www.legislation.gov.uk/ukpga/1996/18/section/71',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('maternity_rights.ordinary_maternity_leave_weeks','maternity_rights','EW','GB','employment_uk','GB',
  26, NULL, 'weeks',
  'Ordinary maternity leave is commonly the first 26 weeks of statutory maternity leave; detailed eligibility/notice rules remain in the regulations.',
  'legislation','ERA 1996 s.71 + Maternity and Parental Leave etc. Regulations 1999','https://www.legislation.gov.uk/uksi/1999/3312',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('maternity_rights.additional_maternity_leave_anchor','maternity_rights','EW','GB','employment_uk','GB',
  NULL, 'additional_maternity_leave_right', 'qualitative',
  'ERA 1996 s.73 anchors additional maternity leave entitlement.',
  'legislation','ERA 1996 s.73','https://www.legislation.gov.uk/ukpga/1996/18/section/73',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('maternity_rights.additional_maternity_leave_weeks','maternity_rights','EW','GB','employment_uk','GB',
  26, NULL, 'weeks',
  'Additional maternity leave is commonly the second 26 weeks of statutory maternity leave; detailed eligibility/notice rules remain in the regulations.',
  'legislation','ERA 1996 s.73 + Maternity and Parental Leave etc. Regulations 1999','https://www.legislation.gov.uk/uksi/1999/3312',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('maternity_rights.total_maternity_leave_weeks','maternity_rights','EW','GB','employment_uk','GB',
  52, NULL, 'weeks',
  'Combined ordinary and additional statutory maternity leave is up to 52 weeks, subject to detailed statutory conditions.',
  'legislation','ERA 1996 ss.71,73 + Maternity and Parental Leave etc. Regulations 1999','https://www.legislation.gov.uk/ukpga/1996/18/part/VIII/chapter/I',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('paternity_rights.paternity_leave_birth_anchor','paternity_rights','EW','GB','employment_uk','GB',
  NULL, 'paternity_leave_birth_entitlement', 'qualitative',
  'ERA 1996 s.80A anchors entitlement to paternity leave for birth cases through regulations.',
  'legislation','ERA 1996 s.80A','https://www.legislation.gov.uk/ukpga/1996/18/section/80A',
  DATE '2002-12-08', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('paternity_rights.paternity_leave_adoption_anchor','paternity_rights','EW','GB','employment_uk','GB',
  NULL, 'paternity_leave_adoption_entitlement', 'qualitative',
  'ERA 1996 s.80B anchors entitlement to paternity leave for adoption cases through regulations.',
  'legislation','ERA 1996 s.80B','https://www.legislation.gov.uk/ukpga/1996/18/section/80B',
  DATE '2002-12-08', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('paternity_rights.rights_during_after_leave','paternity_rights','EW','GB','employment_uk','GB',
  NULL, 'rights_during_and_after_paternity_leave', 'qualitative',
  'ERA 1996 s.80C anchors rights during and after paternity leave.',
  'legislation','ERA 1996 s.80C','https://www.legislation.gov.uk/ukpga/1996/18/section/80C',
  DATE '2002-12-08', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('paternity_rights.bereavement_anchor','paternity_rights','EW','GB','employment_uk','GB',
  NULL, 'bereavement_related_paternity_leave_amendment_anchor', 'qualitative',
  'Paternity Leave (Bereavement) Act 2024 amends ERA 1996 paternity leave provisions.',
  'legislation','Paternity Leave (Bereavement) Act 2024 s.1','https://www.legislation.gov.uk/ukpga/2024/17/section/1',
  DATE '2024-05-24', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('parental_leave.entitlement_anchor','parental_leave','EW','GB','employment_uk','GB',
  NULL, 'parental_leave_entitlement_through_regulations', 'qualitative',
  'ERA 1996 s.76 anchors ordinary parental leave entitlement through regulations.',
  'legislation','ERA 1996 s.76','https://www.legislation.gov.uk/ukpga/1996/18/section/76',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('parental_leave.rights_during_after_leave','parental_leave','EW','GB','employment_uk','GB',
  NULL, 'rights_during_and_after_parental_leave', 'qualitative',
  'ERA 1996 s.77 anchors rights during and after parental leave.',
  'legislation','ERA 1996 s.77','https://www.legislation.gov.uk/ukpga/1996/18/section/77',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('parental_leave.complaint_route','parental_leave','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_route', 'qualitative',
  'ERA 1996 s.80 provides a complaint route where parental leave duties are breached.',
  'legislation','ERA 1996 s.80','https://www.legislation.gov.uk/ukpga/1996/18/section/80',
  DATE '1999-12-15', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('parental_leave.day_one_reform_anchor','parental_leave','EW','GB','employment_uk','GB',
  NULL, 'employment_rights_act_2025_day_one_reform_anchor', 'qualitative',
  'Employment Rights Act 2025 reforms ordinary parental leave; full implementation details must be effective-dated before production use.',
  'legislation','Employment Rights Act 2025 s.15','https://www.legislation.gov.uk/ukpga/2025/36',
  DATE '2025-12-16', NULL, true, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('shared_parental_leave.birth_anchor','shared_parental_leave','EW','GB','employment_uk','GB',
  NULL, 'shared_parental_leave_birth_entitlement', 'qualitative',
  'ERA 1996 s.75E anchors shared parental leave entitlement in birth cases through regulations.',
  'legislation','ERA 1996 s.75E','https://www.legislation.gov.uk/ukpga/1996/18/section/75E',
  DATE '2014-12-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('shared_parental_leave.adoption_anchor','shared_parental_leave','EW','GB','employment_uk','GB',
  NULL, 'shared_parental_leave_adoption_entitlement', 'qualitative',
  'ERA 1996 s.75G anchors shared parental leave entitlement in adoption cases through regulations.',
  'legislation','ERA 1996 s.75G','https://www.legislation.gov.uk/ukpga/1996/18/section/75G',
  DATE '2014-12-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('shared_parental_leave.regulation_power_anchor','shared_parental_leave','EW','GB','employment_uk','GB',
  NULL, 'children_and_families_act_2014_shared_parental_leave_framework', 'qualitative',
  'Children and Families Act 2014 created the shared parental leave framework in ERA 1996.',
  'legislation','Children and Families Act 2014 Part 7','https://www.legislation.gov.uk/ukpga/2014/6/part/7/crossheading/shared-parental-leave',
  DATE '2014-03-13', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true)
ON CONFLICT (rule_key, jurisdiction, effective_from) DO UPDATE SET
  value_numeric=EXCLUDED.value_numeric,
  value_text=EXCLUDED.value_text,
  unit=EXCLUDED.unit,
  description=EXCLUDED.description,
  authority_type=EXCLUDED.authority_type,
  authority_ref=EXCLUDED.authority_ref,
  authority_url=EXCLUDED.authority_url,
  effective_to=EXCLUDED.effective_to,
  is_prospective=EXCLUDED.is_prospective,
  verification_status=EXCLUDED.verification_status,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  domain=EXCLUDED.domain,
  country_code=EXCLUDED.country_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni,
  is_current=EXCLUDED.is_current,
  last_verified_at=now();

INSERT INTO legislation
  (act_title, leg_type, year, chapter, section_ref, jurisdiction, heading,
   body_text, chunk_index, source_url, effective_from, last_verified_at,
   content_hash, country_code, domain, source_type, licence_status,
   parser_type, parent_source_id, jurisdiction_code, legal_system,
   applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni)
VALUES
 ('Employment Rights Act 1996','primary',1996,'18','71','EW','Ordinary maternity leave',
  'Section 71 anchors the right to ordinary maternity leave.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/71', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s71 ordinary maternity leave'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','73','EW','Additional maternity leave',
  'Section 73 anchors the right to additional maternity leave.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/73', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s73 additional maternity leave'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Maternity and Parental Leave etc. Regulations 1999','secondary',1999,'3312','body','EW','Maternity and parental leave framework',
  'The 1999 Regulations contain detailed maternity and parental leave conditions and definitions.',
  0,'https://www.legislation.gov.uk/uksi/1999/3312', DATE '1999-12-15', now(),
  encode(sha256('MPL Regulations 1999 maternity parental leave framework'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','75E','EW','Shared parental leave: birth',
  'Section 75E anchors shared parental leave entitlement in birth cases.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/75E', DATE '2014-12-01', now(),
  encode(sha256('ERA 1996 s75E shared parental leave birth'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','75G','EW','Shared parental leave: adoption',
  'Section 75G anchors shared parental leave entitlement in adoption cases.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/75G', DATE '2014-12-01', now(),
  encode(sha256('ERA 1996 s75G shared parental leave adoption'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','76','EW','Parental leave entitlement',
  'Section 76 anchors ordinary parental leave entitlement through regulations.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/76', DATE '1999-12-15', now(),
  encode(sha256('ERA 1996 s76 parental leave entitlement'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','77','EW','Rights during and after parental leave',
  'Section 77 anchors rights during and after parental leave.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/77', DATE '1999-12-15', now(),
  encode(sha256('ERA 1996 s77 parental leave rights'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80','EW','Complaints to employment tribunals',
  'Section 80 anchors the parental leave complaint route.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80', DATE '1999-12-15', now(),
  encode(sha256('ERA 1996 s80 parental leave complaints'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80A','EW','Paternity leave: birth',
  'Section 80A anchors paternity leave entitlement in birth cases.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80A', DATE '2002-12-08', now(),
  encode(sha256('ERA 1996 s80A paternity leave birth'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80B','EW','Paternity leave: adoption',
  'Section 80B anchors paternity leave entitlement in adoption cases.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80B', DATE '2002-12-08', now(),
  encode(sha256('ERA 1996 s80B paternity leave adoption'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','80C','EW','Rights during and after paternity leave',
  'Section 80C anchors rights during and after paternity leave.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/80C', DATE '2002-12-08', now(),
  encode(sha256('ERA 1996 s80C paternity rights'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Paternity Leave (Bereavement) Act 2024','primary',2024,'17','1','EW','Amendment of ERA 1996 paternity leave provisions',
  'Section 1 amends ERA 1996 paternity leave provisions for bereavement cases.',
  0,'https://www.legislation.gov.uk/ukpga/2024/17/section/1', DATE '2024-05-24', now(),
  encode(sha256('Paternity Leave Bereavement Act 2024 s1'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Children and Families Act 2014','primary',2014,'6','part/7/shared-parental-leave','EW','Shared parental leave',
  'Part 7 contains the shared parental leave framework inserted into ERA 1996.',
  0,'https://www.legislation.gov.uk/ukpga/2014/6/part/7/crossheading/shared-parental-leave', DATE '2014-03-13', now(),
  encode(sha256('Children and Families Act 2014 shared parental leave'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false)
ON CONFLICT (source_url, chunk_index) DO UPDATE SET
  act_title=EXCLUDED.act_title,
  leg_type=EXCLUDED.leg_type,
  year=EXCLUDED.year,
  chapter=EXCLUDED.chapter,
  section_ref=EXCLUDED.section_ref,
  jurisdiction=EXCLUDED.jurisdiction,
  heading=EXCLUDED.heading,
  body_text=EXCLUDED.body_text,
  effective_from=EXCLUDED.effective_from,
  last_verified_at=now(),
  content_hash=EXCLUDED.content_hash,
  country_code=EXCLUDED.country_code,
  domain=EXCLUDED.domain,
  source_type=EXCLUDED.source_type,
  licence_status=EXCLUDED.licence_status,
  parser_type=EXCLUDED.parser_type,
  parent_source_id=EXCLUDED.parent_source_id,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni;

UPDATE employment_modules
SET status = 'partial',
    updated_at = now()
WHERE module_key IN (
  'maternity_rights',
  'paternity_rights',
  'parental_leave',
  'shared_parental_leave'
)
AND status <> 'production';
