-- 064_remaining_employment_module_anchors.sql
-- Initial verified DB coverage for the remaining employment modules that had
-- no verified rules: constructive dismissal, employment contracts/written
-- particulars, fixed-term workers, part-time workers, agency workers, health
-- and safety, trade union rights, and TUPE.
--
-- This completes DB *coverage* for all 24 modules, but NOT production support.
-- Every module here remains partial until full workflows, RAG/Graph RAG,
-- remedies, documents, legal matrix tests, and go-live proof are complete.

INSERT INTO rules
  (rule_key, claim_type, jurisdiction, jurisdiction_code, domain, country_code,
   value_numeric, value_text, unit, description, authority_type, authority_ref, authority_url,
   effective_from, effective_to, is_prospective, verification_status, last_verified_at,
   legal_system, applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni,
   is_current)
VALUES
 ('constructive_dismissal.dismissal_definition','constructive_dismissal','EW','GB','employment_uk','GB',
  NULL, 'employee_terminates_in_response_to_employer_conduct', 'qualitative',
  'Constructive dismissal statutory anchor: employee terminates contract in circumstances where entitled to terminate without notice by reason of employer conduct.',
  'legislation','ERA 1996 s.95(1)(c)','https://www.legislation.gov.uk/ukpga/1996/18/section/95',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('constructive_dismissal.unfair_dismissal_right_anchor','constructive_dismissal','EW','GB','employment_uk','GB',
  NULL, 'right_not_to_be_unfairly_dismissed', 'qualitative',
  'Constructive dismissal unfair-dismissal claims still depend on the right not to be unfairly dismissed and ordinary unfair-dismissal gateways.',
  'legislation','ERA 1996 s.94','https://www.legislation.gov.uk/ukpga/1996/18/section/94',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('constructive_dismissal.time_limit_months','constructive_dismissal','EW','GB','employment_uk','GB',
  3, NULL, 'months',
  'Primary ordinary unfair dismissal time-limit anchor; constructive dismissal needs careful EDT/resignation analysis.',
  'legislation','ERA 1996 s.111','https://www.legislation.gov.uk/ukpga/1996/18/section/111',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('employment_contracts.written_particulars_right','employment_contracts','EW','GB','employment_uk','GB',
  NULL, 'worker_right_to_written_statement_of_particulars', 'qualitative',
  'Worker right to a written statement of employment particulars.',
  'legislation','ERA 1996 s.1','https://www.legislation.gov.uk/ukpga/1996/18/section/1',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('employment_contracts.day_one_particulars_anchor','employment_contracts','EW','GB','employment_uk','GB',
  0, NULL, 'days_service',
  'Written particulars are a day-one worker right under the current statutory scheme.',
  'legislation','ERA 1996 s.1','https://www.legislation.gov.uk/ukpga/1996/18/section/1',
  DATE '2020-04-06', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('employment_contracts.tribunal_reference_route','employment_contracts','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_reference_route', 'qualitative',
  'Employment tribunal may determine particulars/reference complaints under the Part I enforcement provisions.',
  'legislation','ERA 1996 s.11','https://www.legislation.gov.uk/ukpga/1996/18/section/11',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('employment_contracts.section_38_award_anchor','employment_contracts','EW','GB','employment_uk','GB',
  NULL, 'additional_award_possible_where_written_statement_missing_in_qualifying_proceedings', 'qualitative',
  'Employment Act 2002 s.38 anchors additional award consequences where written statement duties are breached in qualifying proceedings.',
  'legislation','Employment Act 2002 s.38','https://www.legislation.gov.uk/ukpga/2002/22/section/38',
  DATE '2004-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('fixed_term_workers.less_favourable_treatment_right','fixed_term_workers','EW','GB','employment_uk','GB',
  NULL, 'right_not_to_be_treated_less_favourably_than_comparable_permanent_employee', 'qualitative',
  'Fixed-term employee right not to be treated less favourably without objective justification.',
  'legislation','Fixed-term Employees Regulations 2002 reg.3','https://www.legislation.gov.uk/uksi/2002/2034/regulation/3',
  DATE '2002-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('fixed_term_workers.objective_justification_anchor','fixed_term_workers','EW','GB','employment_uk','GB',
  NULL, 'objective_justification_possible', 'qualitative',
  'Less favourable treatment may be objectively justified under the Regulations.',
  'legislation','Fixed-term Employees Regulations 2002 reg.3','https://www.legislation.gov.uk/uksi/2002/2034/regulation/3',
  DATE '2002-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('fixed_term_workers.successive_contracts_years','fixed_term_workers','EW','GB','employment_uk','GB',
  4, NULL, 'years',
  'Successive fixed-term contracts may become permanent after four years unless continued fixed-term use is objectively justified.',
  'legislation','Fixed-term Employees Regulations 2002 reg.8','https://www.legislation.gov.uk/uksi/2002/2034/regulation/8',
  DATE '2002-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('part_time_workers.less_favourable_treatment_right','part_time_workers','EW','GB','employment_uk','GB',
  NULL, 'right_not_to_be_treated_less_favourably_than_comparable_full_time_worker', 'qualitative',
  'Part-time worker right not to be treated less favourably than comparable full-time worker.',
  'legislation','Part-time Workers Regulations 2000 reg.5','https://www.legislation.gov.uk/uksi/2000/1551/regulation/5',
  DATE '2000-07-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('part_time_workers.objective_justification_anchor','part_time_workers','EW','GB','employment_uk','GB',
  NULL, 'objective_justification_possible', 'qualitative',
  'Less favourable treatment may be justified on objective grounds.',
  'legislation','Part-time Workers Regulations 2000 reg.5','https://www.legislation.gov.uk/uksi/2000/1551/regulation/5',
  DATE '2000-07-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('part_time_workers.complaint_route','part_time_workers','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_route', 'qualitative',
  'Regulation 8 anchors the employment tribunal complaint route.',
  'legislation','Part-time Workers Regulations 2000 reg.8','https://www.legislation.gov.uk/uksi/2000/1551/regulation/8',
  DATE '2000-07-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('agency_workers.equal_treatment_after_qualifying_period','agency_workers','EW','GB','employment_uk','GB',
  NULL, 'equal_treatment_basic_working_and_employment_conditions_after_qualifying_period', 'qualitative',
  'Agency worker equal treatment right after completing the qualifying period.',
  'legislation','Agency Workers Regulations 2010 reg.5','https://www.legislation.gov.uk/uksi/2010/93/regulation/5',
  DATE '2011-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('agency_workers.qualifying_period_weeks','agency_workers','EW','GB','employment_uk','GB',
  12, NULL, 'weeks',
  'Agency worker qualifying period for regulation 5 rights.',
  'legislation','Agency Workers Regulations 2010 reg.7','https://www.legislation.gov.uk/uksi/2010/93/regulation/7',
  DATE '2011-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('agency_workers.tribunal_complaint_route','agency_workers','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_route', 'qualitative',
  'Regulation 18 anchors the employment tribunal complaint route.',
  'legislation','Agency Workers Regulations 2010 reg.18','https://www.legislation.gov.uk/uksi/2010/93/regulation/18',
  DATE '2011-10-01', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('health_and_safety.detriment_protection','health_and_safety','EW','GB','employment_uk','GB',
  NULL, 'right_not_to_suffer_health_and_safety_detriment', 'qualitative',
  'Worker/employee protection against health-and-safety detriment.',
  'legislation','ERA 1996 s.44','https://www.legislation.gov.uk/ukpga/1996/18/section/44',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('health_and_safety.automatic_unfair_dismissal','health_and_safety','EW','GB','employment_uk','GB',
  NULL, 'dismissal_for_health_and_safety_reason_automatically_unfair', 'qualitative',
  'Automatic unfair dismissal anchor for specified health and safety reasons.',
  'legislation','ERA 1996 s.100','https://www.legislation.gov.uk/ukpga/1996/18/section/100',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('health_and_safety.complaint_route','health_and_safety','EW','GB','employment_uk','GB',
  NULL, 'employment_tribunal_complaint_route_for_detriment', 'qualitative',
  'ERA 1996 s.48 provides complaint route for detriment claims including s.44.',
  'legislation','ERA 1996 s.48','https://www.legislation.gov.uk/ukpga/1996/18/section/48',
  DATE '1996-08-22', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('trade_union_rights.detriment_protection','trade_union_rights','EW','GB','employment_uk','GB',
  NULL, 'right_not_to_suffer_detriment_for_trade_union_membership_or_activities', 'qualitative',
  'Protection from detriment related to trade union membership or activities.',
  'legislation','TULRCA 1992 s.146','https://www.legislation.gov.uk/ukpga/1992/52/section/146',
  DATE '1992-10-16', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('trade_union_rights.automatic_unfair_dismissal','trade_union_rights','EW','GB','employment_uk','GB',
  NULL, 'dismissal_for_trade_union_membership_or_activities_automatically_unfair', 'qualitative',
  'Automatic unfair dismissal anchor for trade union membership or activities.',
  'legislation','TULRCA 1992 s.152','https://www.legislation.gov.uk/ukpga/1992/52/section/152',
  DATE '1992-10-16', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('trade_union_rights.time_off_duties','trade_union_rights','EW','GB','employment_uk','GB',
  NULL, 'reasonable_time_off_for_trade_union_duties', 'qualitative',
  'Time off for trade union duties anchor.',
  'legislation','TULRCA 1992 s.168','https://www.legislation.gov.uk/ukpga/1992/52/section/168',
  DATE '1992-10-16', NULL, false, 'verified', now(),
  'Great Britain', true, true, true, false, true),
 ('tupe.relevant_transfer_anchor','tupe','EW','GB','employment_uk','GB',
  NULL, 'relevant_transfer_scope_anchor', 'qualitative',
  'TUPE relevant transfer scope anchor.',
  'legislation','TUPE Regulations 2006 reg.3','https://www.legislation.gov.uk/uksi/2006/246/regulation/3',
  DATE '2006-04-06', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('tupe.automatic_transfer_anchor','tupe','EW','GB','employment_uk','GB',
  NULL, 'contracts_transfer_to_transferee', 'qualitative',
  'TUPE automatic transfer of contracts anchor.',
  'legislation','TUPE Regulations 2006 reg.4','https://www.legislation.gov.uk/uksi/2006/246/regulation/4',
  DATE '2006-04-06', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('tupe.dismissal_anchor','tupe','EW','GB','employment_uk','GB',
  NULL, 'dismissal_connected_to_transfer_anchor', 'qualitative',
  'TUPE transfer-related dismissal anchor.',
  'legislation','TUPE Regulations 2006 reg.7','https://www.legislation.gov.uk/uksi/2006/246/regulation/7',
  DATE '2006-04-06', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true),
 ('tupe.information_consultation_anchor','tupe','EW','GB','employment_uk','GB',
  NULL, 'information_and_consultation_duties_anchor', 'qualitative',
  'TUPE information and consultation duties anchor.',
  'legislation','TUPE Regulations 2006 reg.13','https://www.legislation.gov.uk/uksi/2006/246/regulation/13',
  DATE '2006-04-06', NULL, false, 'verified', now(),
  'United Kingdom', true, true, true, true, true)
ON CONFLICT (rule_key, jurisdiction, effective_from) DO UPDATE SET
  value_numeric=EXCLUDED.value_numeric,
  value_text=EXCLUDED.value_text,
  unit=EXCLUDED.unit,
  description=EXCLUDED.description,
  authority_type=EXCLUDED.authority_type,
  authority_ref=EXCLUDED.authority_ref,
  authority_url=EXCLUDED.authority_url,
  effective_to=EXCLUDED.effective_to,
  is_prospective=EXCLUDED.is_prospective,
  verification_status=EXCLUDED.verification_status,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  domain=EXCLUDED.domain,
  country_code=EXCLUDED.country_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni,
  is_current=EXCLUDED.is_current,
  last_verified_at=now();

INSERT INTO legislation
  (act_title, leg_type, year, chapter, section_ref, jurisdiction, heading,
   body_text, chunk_index, source_url, effective_from, last_verified_at,
   content_hash, country_code, domain, source_type, licence_status,
   parser_type, parent_source_id, jurisdiction_code, legal_system,
   applies_to_gb, applies_to_england_wales, applies_to_scotland, applies_to_ni)
VALUES
 ('Employment Rights Act 1996','primary',1996,'18','1','EW','Statement of initial employment particulars',
  'Section 1 anchors the worker right to a written statement of employment particulars.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/1', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s1 written particulars'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','11','EW','References to employment tribunals',
  'Section 11 anchors tribunal reference routes for employment particulars disputes.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/11', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s11 particulars tribunal route'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','44','EW','Health and safety cases',
  'Section 44 anchors detriment protection in health and safety cases.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/44', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s44 health safety detriment'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','95','EW','Circumstances in which an employee is dismissed',
  'Section 95 includes constructive dismissal at subsection (1)(c).',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/95', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s95 constructive dismissal'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Rights Act 1996','primary',1996,'18','100','EW','Health and safety dismissals',
  'Section 100 anchors automatic unfair dismissal protection for specified health and safety reasons.',
  0,'https://www.legislation.gov.uk/ukpga/1996/18/section/100', DATE '1996-08-22', now(),
  encode(sha256('ERA 1996 s100 health safety dismissal'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Employment Act 2002','primary',2002,'22','38','EW','Failure to give statement of employment particulars etc.',
  'Section 38 anchors additional award consequences where written statement duties are breached in qualifying proceedings.',
  0,'https://www.legislation.gov.uk/ukpga/2002/22/section/38', DATE '2004-10-01', now(),
  encode(sha256('Employment Act 2002 s38 written particulars award'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Fixed-term Employees Regulations 2002','secondary',2002,'2034','regulation/3','EW','Less favourable treatment',
  'Regulation 3 anchors fixed-term employee protection from less favourable treatment.',
  0,'https://www.legislation.gov.uk/uksi/2002/2034/regulation/3', DATE '2002-10-01', now(),
  encode(sha256('Fixed-term Employees Regulations 2002 reg3'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Fixed-term Employees Regulations 2002','secondary',2002,'2034','regulation/8','EW','Successive fixed-term contracts',
  'Regulation 8 anchors limits on successive fixed-term contracts.',
  0,'https://www.legislation.gov.uk/uksi/2002/2034/regulation/8', DATE '2002-10-01', now(),
  encode(sha256('Fixed-term Employees Regulations 2002 reg8'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Part-time Workers Regulations 2000','secondary',2000,'1551','regulation/5','EW','Less favourable treatment of part-time workers',
  'Regulation 5 anchors part-time worker protection from less favourable treatment.',
  0,'https://www.legislation.gov.uk/uksi/2000/1551/regulation/5', DATE '2000-07-01', now(),
  encode(sha256('Part-time Workers Regulations 2000 reg5'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Part-time Workers Regulations 2000','secondary',2000,'1551','regulation/8','EW','Complaints to employment tribunals',
  'Regulation 8 anchors part-time worker tribunal complaints.',
  0,'https://www.legislation.gov.uk/uksi/2000/1551/regulation/8', DATE '2000-07-01', now(),
  encode(sha256('Part-time Workers Regulations 2000 reg8'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Agency Workers Regulations 2010','secondary',2010,'93','regulation/5','EW','Rights of agency workers in relation to basic working and employment conditions',
  'Regulation 5 anchors agency worker equal treatment rights.',
  0,'https://www.legislation.gov.uk/uksi/2010/93/regulation/5', DATE '2011-10-01', now(),
  encode(sha256('Agency Workers Regulations 2010 reg5'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Agency Workers Regulations 2010','secondary',2010,'93','regulation/7','EW','Qualifying period',
  'Regulation 7 anchors the agency worker qualifying period.',
  0,'https://www.legislation.gov.uk/uksi/2010/93/regulation/7', DATE '2011-10-01', now(),
  encode(sha256('Agency Workers Regulations 2010 reg7'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Agency Workers Regulations 2010','secondary',2010,'93','regulation/18','EW','Employment tribunals',
  'Regulation 18 anchors agency worker tribunal complaints.',
  0,'https://www.legislation.gov.uk/uksi/2010/93/regulation/18', DATE '2011-10-01', now(),
  encode(sha256('Agency Workers Regulations 2010 reg18'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Trade Union and Labour Relations (Consolidation) Act 1992','primary',1992,'52','146','EW','Detriment on grounds related to union membership or activities',
  'Section 146 anchors detriment protection related to trade union membership or activities.',
  0,'https://www.legislation.gov.uk/ukpga/1992/52/section/146', DATE '1992-10-16', now(),
  encode(sha256('TULRCA 1992 s146 trade union detriment'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Trade Union and Labour Relations (Consolidation) Act 1992','primary',1992,'52','152','EW','Dismissal on grounds related to union membership or activities',
  'Section 152 anchors automatic unfair dismissal related to trade union membership or activities.',
  0,'https://www.legislation.gov.uk/ukpga/1992/52/section/152', DATE '1992-10-16', now(),
  encode(sha256('TULRCA 1992 s152 trade union dismissal'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Trade Union and Labour Relations (Consolidation) Act 1992','primary',1992,'52','168','EW','Time off for carrying out trade union duties',
  'Section 168 anchors time off for trade union duties.',
  0,'https://www.legislation.gov.uk/ukpga/1992/52/section/168', DATE '1992-10-16', now(),
  encode(sha256('TULRCA 1992 s168 trade union duties time off'::bytea), 'hex'),
  'GB','employment_uk','primary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','Great Britain',true,true,true,false),
 ('Transfer of Undertakings (Protection of Employment) Regulations 2006','secondary',2006,'246','regulation/3','EW','Relevant transfer',
  'Regulation 3 anchors the relevant transfer definition.',
  0,'https://www.legislation.gov.uk/uksi/2006/246/regulation/3', DATE '2006-04-06', now(),
  encode(sha256('TUPE 2006 reg3 relevant transfer'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','United Kingdom',true,true,true,true),
 ('Transfer of Undertakings (Protection of Employment) Regulations 2006','secondary',2006,'246','regulation/4','EW','Effect of relevant transfer on contracts of employment',
  'Regulation 4 anchors automatic transfer of contracts.',
  0,'https://www.legislation.gov.uk/uksi/2006/246/regulation/4', DATE '2006-04-06', now(),
  encode(sha256('TUPE 2006 reg4 contracts transfer'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','United Kingdom',true,true,true,true),
 ('Transfer of Undertakings (Protection of Employment) Regulations 2006','secondary',2006,'246','regulation/7','EW','Dismissal of employee because of relevant transfer',
  'Regulation 7 anchors transfer-related dismissal protection.',
  0,'https://www.legislation.gov.uk/uksi/2006/246/regulation/7', DATE '2006-04-06', now(),
  encode(sha256('TUPE 2006 reg7 dismissal'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','United Kingdom',true,true,true,true),
 ('Transfer of Undertakings (Protection of Employment) Regulations 2006','secondary',2006,'246','regulation/13','EW','Duty to inform and consult representatives',
  'Regulation 13 anchors information and consultation duties.',
  0,'https://www.legislation.gov.uk/uksi/2006/246/regulation/13', DATE '2006-04-06', now(),
  encode(sha256('TUPE 2006 reg13 inform consult'::bytea), 'hex'),
  'GB','employment_uk','secondary_legislation','GRANTED','seeded_text','legislation_gov_uk','GB','United Kingdom',true,true,true,true)
ON CONFLICT (source_url, chunk_index) DO UPDATE SET
  act_title=EXCLUDED.act_title,
  leg_type=EXCLUDED.leg_type,
  year=EXCLUDED.year,
  chapter=EXCLUDED.chapter,
  section_ref=EXCLUDED.section_ref,
  jurisdiction=EXCLUDED.jurisdiction,
  heading=EXCLUDED.heading,
  body_text=EXCLUDED.body_text,
  effective_from=EXCLUDED.effective_from,
  last_verified_at=now(),
  content_hash=EXCLUDED.content_hash,
  country_code=EXCLUDED.country_code,
  domain=EXCLUDED.domain,
  source_type=EXCLUDED.source_type,
  licence_status=EXCLUDED.licence_status,
  parser_type=EXCLUDED.parser_type,
  parent_source_id=EXCLUDED.parent_source_id,
  jurisdiction_code=EXCLUDED.jurisdiction_code,
  legal_system=EXCLUDED.legal_system,
  applies_to_gb=EXCLUDED.applies_to_gb,
  applies_to_england_wales=EXCLUDED.applies_to_england_wales,
  applies_to_scotland=EXCLUDED.applies_to_scotland,
  applies_to_ni=EXCLUDED.applies_to_ni;

UPDATE employment_modules
SET status = 'partial',
    updated_at = now()
WHERE module_key IN (
  'agency_workers',
  'constructive_dismissal',
  'employment_contracts',
  'fixed_term_workers',
  'health_and_safety',
  'part_time_workers',
  'trade_union_rights',
  'tupe'
)
AND status <> 'production';
